# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: bottom

# Miscellaneous
google_analytics:
favicon: /favicon.png
github:
twitter:
# eg: google_plus: "12345678".
google_plus:
# no icon
bitbucket:
